"use client"
import { Roboto } from "next/font/google";
import Header from "./_componaten/header/Header";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css"
import Footer from "./_componaten/footer/Footer";
import NextTopLoader from "nextjs-toploader";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";

import { useState } from "react";
import { CartContext } from "./_context/CartContext";


const inter = Roboto({ subsets: ["latin"],weight:["100","300","400"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [card,setCard]=useState([])
  return (
    // <ClerkProvider>
      <CartContext.Provider value={{card,setCard}}>
        <html lang="en">
          <body className={inter.className}>
          <NextTopLoader color="blue"/> 
            {/* <Header/> */}
            {children}
            {/* <Footer/> */}
            </body>
        </html>
      </CartContext.Provider>
    // </ClerkProvider> 
  ); 
}
